#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

# Symlink bin command to /usr/bin
rm -f /usr/bin/aseprite
ln -s /usr/share/aseprite/aseprite /usr/bin/aseprite
if hash desktop-file-install 2>/dev/null; then
        desktop-file-install /usr/share/applications/aseprite.desktop
fi
