#!/usr/bin/env bash

rm -f /usr/bin/aseprite
ln -s /usr/share/aseprite/aseprite /usr/bin/aseprite
if hash desktop-file-install 2>/dev/null; then
        desktop-file-install /usr/share/applications/aseprite.desktop
fi
