name: Update package version
on:
  repository_dispatch:
     types: [new-release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Get versions
        run: |
          cat deb-frame/DEBIAN/control | grep Version | cut -d " " -f 2 > original.txt
          curl -sL https://api.github.com/repos/aseprite/aseprite/releases/latest --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r ".tag_name" | cut -d "v" -f 2 > source.txt
      - name: var
        id: var
        run: |
          echo "original=$(cat deb-frame/DEBIAN/control | grep Version | cut -d " " -f 2)" >> "$GITHUB_OUTPUT"
          echo "source=$(curl -sL https://api.github.com/repos/aseprite/aseprite/releases/latest --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r ".tag_name" | cut -d "v" -f 2)" >> "$GITHUB_OUTPUT"
      - name: Compare
        id: check
        run: echo "diff=$(if diff original.txt source.txt -q; then echo "false"; fi)" >> "$GITHUB_OUTPUT"
      - name: Patch it
        if: steps.check.outputs.diff != 'false'
        run: |
          cd deb-frame/DEBIAN
          sed -i 's/${{ steps.var.outputs.original }}/${{ steps.var.outputs.source }}/g' control
      - name: Import GPG
        if: steps.check.outputs.diff != 'false'
        uses: crazy-max/ghaction-import-gpg@v1.4.1
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_committer_name: Insouciant21
          git_committer_email: 48847364+Insouciant21@users.noreply.github.com
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Push File
        if: steps.check.outputs.diff != 'false'
        run: |
          git add deb-frame/
          git commit -S -m "new version released"
          git push
      - name: Repository Dispatch
        if: steps.check.outputs.diff != 'false'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.work1 }}
          event-type: build
